//! Generate a small but real Emacs plugin and write it to
//! `examples/out/ferrel-hello.el`.
//!
//! Run with: `cargo run --example hello`

use ferrel::*;

fn main() -> std::io::Result<()> {
    let pkg = Package::new("ferrel-hello", "A greeting command generated from Rust.")
        .author("ferrel")
        .version("0.1.0")
        .emacs_version("27.1")
        .keyword("convenience")
        .commentary(
            "This file was generated by ferrel, a typed Rust eDSL for Emacs Lisp.\n\
             Do not edit it by hand: edit the Rust source and regenerate.",
        )
        // A user-customizable greeting. Typed as a string at compile time.
        .form(defcustom(
            "ferrel-hello-greeting",
            string("Hello from Rust-generated Elisp!"),
            "Greeting shown by `ferrel-hello'.",
            "string",
            "ferrel-hello",
        ))
        // An interactive command that messages the greeting.
        .defun(
            Defun::new("ferrel-hello")
                .doc("Display the configured greeting in the echo area.")
                .interactive()
                .body([message(var::<Str>("ferrel-hello-greeting"), [])]),
        )
        // An interactive command that inserts the greeting at point.
        .defun(
            Defun::new("ferrel-hello-insert")
                .doc("Insert the configured greeting at point.")
                .interactive()
                .body([insert(var::<Str>("ferrel-hello-greeting"))]),
        )
        // A pure function showing typed arithmetic: (a + b) * 2.
        // `add(string(...), ...)` would not compile, which is the whole point.
        .defun(
            Defun::new("ferrel-hello-double-sum")
                .doc("Return twice the sum of A and B.")
                .param("a")
                .param("b")
                .body([mul(add(var::<Int>("a"), var::<Int>("b")), int(2))]),
        )
        // Bind the greeting command to a key.
        .form(global_set_key("C-c h", "ferrel-hello"));

    let el = pkg.render();
    println!("{el}");

    let out = concat_path("examples/out/ferrel-hello.el");
    pkg.write(&out)?;
    eprintln!("wrote {out}");
    Ok(())
}

/// Resolve a path relative to the crate manifest directory so the example
/// works regardless of the current working directory.
fn concat_path(rel: &str) -> String {
    format!("{}/{}", env!("CARGO_MANIFEST_DIR"), rel)
}
